language: python
sudo: true
dist: trusty

python:
  - "2.7"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"

install:
  - pip install coveralls
  - cd contrib/python && python ./setup.py install && cd ../../

branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO: github.com/codeplaysoftware/visioncpp.git

addons:
  apt:
    packages:
      - doxygen
      - graphviz
before_script:
  - chmod +x ./scripts/travis_build_docs.sh
  - chmod +x ./scripts/travis_deploy_docs.sh

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/travis_build_docs.sh; fi'
  - cd contrib/python && coverage run --source=visioncpp setup.py test && cd ../../

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/travis_deploy_docs.sh; fi'
  - cd contrib/python && coveralls && cd ../../
